# WEB SCRAPING
### Ayush Karn - 17BCE2381

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

%matplotlib inline

In [2]:
seed_urls = ['https://inshorts.com/en/read/technology',
             'https://inshorts.com/en/read/sports',
             'https://inshorts.com/en/read/world']

def build_dataset(seed_urls):
    news_data = []
    for url in seed_urls:
        news_category = url.split('/')[-1]
        data = requests.get(url)
        soup = BeautifulSoup(data.content, 'html.parser')
        
        news_articles = [{'news_headline': headline.find('span', 
                                                         attrs={"itemprop": "headline"}).string,
                          'news_article': article.find('div', 
                                                       attrs={"itemprop": "articleBody"}).string,
                          'news_category': news_category}
                         
                            for headline, article in 
                             zip(soup.find_all('div', 
                                               class_=["news-card-title news-right-box"]),
                                 soup.find_all('div', 
                                               class_=["news-card-content news-right-box"]))
                        ]
        news_data.extend(news_articles)
        
    df =  pd.DataFrame(news_data)
    df = df[['news_headline', 'news_article', 'news_category']]
    return df

In [3]:
news_df = build_dataset(seed_urls)
news_df.head(10)

,news_headline,news_article,news_category
0,"Indian-origin man stalked Apple CEO, tried to ...",Apple has been granted a temporary restraining...,technology
1,Man electrocuted as he plugs badly insulated p...,A man believed to be aged 20 was electrocuted ...,technology
2,Google removes 600 apps from Play Store for sh...,Google announced that it has removed nearly 60...,technology
3,Machine at Delhi station dispenses free platfo...,A machine that dispenses free platform tickets...,technology
4,Private WhatsApp group invite links available ...,A German journalist reported that links of pri...,technology
5,300 Oracle staff stop work to protest Larry El...,Around 300 Oracle employees stopped work to pr...,technology
6,AI discovers antibiotic that can fight drug-re...,Researchers at MIT have reported that a machin...,technology
7,Amazon removing listings for products claiming...,Amazon is removing listings of products claimi...,technology
8,"Microsoft to invest $1.1 bn in Mexico, build t...",Microsoft CEO Satya Nadella has announced that...,technology
9,Twitter suspends 70 accounts that posted ident...,Twitter has suspended 70 accounts for posting ...,technology